const challenges=[['30 perc telefon nélkül.','Tedd félre a telefonod. Kapcsold ki az értesítéseket, és tölts el fél órát úgy, hogy nem nézed meg.'],['20 perc séta cél nélkül.','Nem edzés, nem bevásárlás, nem ügyintézés. Csak séta. Figyeld meg, mi történik körülötted.'],['Igyál meg egy kávét vagy teát képernyő nélkül.','Ne telefonozz, ne dolgozz, ne olvass. Csak idd meg, és figyeld meg az ízét.'],['Ülj le 5 percre és ne csinálj semmit.','Nem kell meditálnod. Nem kell teljesítened. Csak ülj és lélegezz.'],['Vacsorázz képernyő nélkül.','Tedd el a telefont, kapcsold ki a tévét, és figyelj arra, akivel együtt vagy.'],['Menj ki 10 percre a természetbe.','Nézz körül. Hallgasd meg a környezeted. Ne fényképezz, ne posztolj. Csak legyél ott.'],['Ma egy feladatot csinálj egyszerre.','Kapcsold ki a fölösleges füleket és értesítéseket. Egy dolog. Aztán a következő.']];
let ci=Number(localStorage.getItem('capyChallenge')||0),done=Number(localStorage.getItem('capyWeek')||0);const $=s=>document.querySelector(s);
function renderChallenge(){if(!$('#challenge-title'))return;$('#challenge-title').textContent=challenges[ci][0];$('#challenge-text').textContent=challenges[ci][1];$('#progress').style.width=Math.min(done/7*100,100)+'%';$('#status').textContent=`${done} / 7 teljesítve ezen a héten`}
if($('#next'))$('#next').onclick=()=>{ci=(ci+1)%challenges.length;localStorage.setItem('capyChallenge',ci);renderChallenge();toast('🦫 Új kihívás érkezett.')};
if($('#done'))$('#done').onclick=()=>{done=Math.min(7,done+1);localStorage.setItem('capyWeek',done);renderChallenge();toast('✓ Szép volt. Egy apró lépés is számít.')};renderChallenge();
let cat='Mind',query='';
function cardHTML(a,featured=false){return `<article class="${featured?'featured-card':'article-card'}"><div class="article-meta"><span class="tag">${a.cat}</span><span>${a.minutes} perc</span></div><h3>${a.title}</h3><p>${a.excerpt}</p><a class="read-link" href="articles/${a.slug}.html">Elolvasom →</a></article>`}
function renderFeatured(){const box=$('#featured-articles');if(!box)return;box.innerHTML=articles.slice(0,3).map(a=>cardHTML(a,true)).join('')}
function renderArticles(){const box=$('#articles');if(!box)return;const empty=$('#empty');let list=articles.filter(a=>(cat==='Mind'||a.cat===cat)&&(`${a.title} ${a.excerpt} ${a.cat}`.toLowerCase().includes(query.toLowerCase())));box.innerHTML=list.map(a=>cardHTML(a,false)).join('');empty.style.display=list.length?'none':'block'}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat;renderArticles()});if($('#search'))$('#search').oninput=e=>{query=e.target.value;renderArticles()};document.querySelectorAll('[data-filter]').forEach(a=>a.onclick=()=>{cat=a.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));renderArticles()});renderArticles();renderFeatured();
const nav=document.querySelector('.nav');if($('.hamb'))$('.hamb').onclick=()=>nav.classList.toggle('open');document.querySelectorAll('.nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
if($('#signup'))$('#signup').onsubmit=e=>{e.preventDefault();e.target.reset();toast('🦫 Feliratkozás rögzítve — ez továbbra is demó.');};function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}if($('#year'))$('#year').textContent=new Date().getFullYear();
